services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: auth_admin
      POSTGRES_PASSWORD: auth_password
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  auth:
    build:
      context: ./auth
    ports:
      - "50051:50051"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://auth_admin:auth_password@db:5432/auth_service

  score:
    build:
      context: ./score
    ports:
      - "50052:50052"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://auth_admin:auth_password@db:5432/auth_service
      - THRESHOLD_SCORE=0.5

  composition:
    build:
      context: ./composition
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - score
    environment:
      - AUTH_SERVICE_URL=grpc://auth:50051
      - SCORE_SERVICE_URL=grpc://score:50052
    volumes:
      - ./auth:/app/auth
      - ./score:/app/score

  nginx:
    image: nginx:latest
    container_name: nginx_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - composition