# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import score_service_pb2 as score__service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in score_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetScore = channel.unary_unary(
                '/score.ScoreService/GetScore',
                request_serializer=score__service__pb2.GetScoreRequest.SerializeToString,
                response_deserializer=score__service__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.RegenerateScore = channel.unary_unary(
                '/score.ScoreService/RegenerateScore',
                request_serializer=score__service__pb2.RegenerateScoreRequest.SerializeToString,
                response_deserializer=score__service__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.EvaluateScore = channel.unary_unary(
                '/score.ScoreService/EvaluateScore',
                request_serializer=score__service__pb2.EvaluateScoreRequest.SerializeToString,
                response_deserializer=score__service__pb2.EvaluateScoreResponse.FromString,
                _registered_method=True)
        self.GenerateScore = channel.unary_unary(
                '/score.ScoreService/GenerateScore',
                request_serializer=score__service__pb2.GenerateScoreRequest.SerializeToString,
                response_deserializer=score__service__pb2.ScoreResponse.FromString,
                _registered_method=True)


class ScoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegenerateScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScore,
                    request_deserializer=score__service__pb2.GetScoreRequest.FromString,
                    response_serializer=score__service__pb2.ScoreResponse.SerializeToString,
            ),
            'RegenerateScore': grpc.unary_unary_rpc_method_handler(
                    servicer.RegenerateScore,
                    request_deserializer=score__service__pb2.RegenerateScoreRequest.FromString,
                    response_serializer=score__service__pb2.ScoreResponse.SerializeToString,
            ),
            'EvaluateScore': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateScore,
                    request_deserializer=score__service__pb2.EvaluateScoreRequest.FromString,
                    response_serializer=score__service__pb2.EvaluateScoreResponse.SerializeToString,
            ),
            'GenerateScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateScore,
                    request_deserializer=score__service__pb2.GenerateScoreRequest.FromString,
                    response_serializer=score__service__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'score.ScoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('score.ScoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/score.ScoreService/GetScore',
            score__service__pb2.GetScoreRequest.SerializeToString,
            score__service__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegenerateScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/score.ScoreService/RegenerateScore',
            score__service__pb2.RegenerateScoreRequest.SerializeToString,
            score__service__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/score.ScoreService/EvaluateScore',
            score__service__pb2.EvaluateScoreRequest.SerializeToString,
            score__service__pb2.EvaluateScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/score.ScoreService/GenerateScore',
            score__service__pb2.GenerateScoreRequest.SerializeToString,
            score__service__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
