# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetScore = channel.unary_unary(
                '/app.ScoreService/GetScore',
                request_serializer=services__pb2.LoginRequest.SerializeToString,
                response_deserializer=services__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.GetPassword = channel.unary_unary(
                '/app.ScoreService/GetPassword',
                request_serializer=services__pb2.LoginRequest.SerializeToString,
                response_deserializer=services__pb2.PasswordResponse.FromString,
                _registered_method=True)
        self.GetGud = channel.unary_unary(
                '/app.ScoreService/GetGud',
                request_serializer=services__pb2.LoginRequest.SerializeToString,
                response_deserializer=services__pb2.ScoreResponse.FromString,
                _registered_method=True)


class ScoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScore,
                    request_deserializer=services__pb2.LoginRequest.FromString,
                    response_serializer=services__pb2.ScoreResponse.SerializeToString,
            ),
            'GetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPassword,
                    request_deserializer=services__pb2.LoginRequest.FromString,
                    response_serializer=services__pb2.PasswordResponse.SerializeToString,
            ),
            'GetGud': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGud,
                    request_deserializer=services__pb2.LoginRequest.FromString,
                    response_serializer=services__pb2.ScoreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.ScoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.ScoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ScoreService/GetScore',
            services__pb2.LoginRequest.SerializeToString,
            services__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ScoreService/GetPassword',
            services__pb2.LoginRequest.SerializeToString,
            services__pb2.PasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.ScoreService/GetGud',
            services__pb2.LoginRequest.SerializeToString,
            services__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authorize = channel.unary_unary(
                '/app.AuthService/Authorize',
                request_serializer=services__pb2.AuthRequest.SerializeToString,
                response_deserializer=services__pb2.AuthResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Authorize,
                    request_deserializer=services__pb2.AuthRequest.FromString,
                    response_serializer=services__pb2.AuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.AuthService/Authorize',
            services__pb2.AuthRequest.SerializeToString,
            services__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
